#!/bin/bash

source config


echo "=== Deploy minipage hub ==="
echo ""

echo "Creating configuration directory $CONFIG_DIR"
mkdir -p $CONFIG_DIR
mkdir -p $CERTS_DIR

echo "Creating network bridge..."
docker network create minipage-network > /dev/null

echo "Starting proxy..."
docker run -d \
    --name $PROXY_CONTAINER_NAME \
    --net $NETWORK_BRIDGE \
    -p 80:80 -p 443:443 \
    -v $CERTS_DIR:/etc/nginx/certs:rw \
    -v /usr/share/nginx/html \
    -v /etc/nginx/vhost.d \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    jwilder/nginx-proxy > /dev/null


echo "Starting certs agent..."
docker run -d \
    --name $CERTS_AGENT_CONTAINER_NAME \
    --net $NETWORK_BRIDGE \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    --volumes-from $PROXY_CONTAINER_NAME \
    jrcs/letsencrypt-nginx-proxy-companion > /dev/null


echo "Deployment done."
