#!/bin/bash


source config

echo "=== Minipage hub undeploy ==="
echo ""

echo "Remove configuration directory $CONFIG_DIR"
rm -rf $CONFIG_DIR

echo "Removing proxy container..."
docker stop $PROXY_CONTAINER_NAME
docker rm $PROXY_CONTAINER_NAME

echo "Removing certs agent container..."
docker stop $CERTS_AGENT_CONTAINER_NAME
docker rm $CERTS_AGENT_CONTAINER_NAME


echo "Removing network bridge..."
docker network rm $NETWORK_BRIDGE


echo "Undeployment done."
